# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fpSrie1OJTf34jHfsSebXBAHexzAG/qHfOoKy3/RhCvxhQ51B1epuApBQXII7KU5Eaetuy9a+rj1KRD5HEvrbJkN7mcVDzhefu0si0T77SFuuQofxb2NzeOPDo0rbtkSDjDTbLUq9Ab5VjUY7vPdQJ+1srRTZv0ExGxW5K8iOaPphJ98Qm/1vCNZZlLPQSfdMLlGaxTcX99KChVGgkruGfdmBSZO9wTxYXgiN0YjrDbzprleG0OLXMgCZt97Gfybk3UIjlHoCeL3HvTwLAhylhSRcqCDkdoGciEmNF4K+TNUnodg1MOGjKElDV/jDA5e9YMZLewVEdogk96DQpytNoWf/byu4T03wYUz7i/UKYrhksCt9g66slXDtScjq0edteWbH8WfR3pi0EpHDGqBxlx/cDNML6e7h/vFtKi3Qnk/vcdTvG3gPPbCEZGQFuNyN6bFTLzvrENlD1m04WNdxg/Vzt54sulUKCa8ub+g3AGTgaUdScyXHuX9+7J2D74sICN1xNSvUDUBu5EPMkrj5Xdi5BywYY1M/VN0i2q7C7Aq8JyRuPQv8emBmzdm5OrsLae8FR2rQLCs/pZsE5dRegYXAeRrg8psGg6FdLrvfSu5lAwp2FrecwBj+EB1yPvHEKrZSMgXxcKbQT60oDe103Wj6tfRUThRAZOROrRzNgE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
