travis:
  secure:
    BINSTAR_TOKEN: JME0Y3RUp+sFeKYCiUPnFdjiUP1fwf7ONoySvHoIpKjCuCIGZH0fWDM99CbD0aQk/akzOYpkgaQQYCA1NPx/mgmLB7wUgznGh/Yjsf+mpyQCxtxGqpmMusaY522ecjlVcoXupYTwiL+JezHeQaXcvokER9MBCppUtgNhbLQXBt/8Mhyyrds7maNHUfsxgjXcfh2RYZAJorsGHftHCKgQCxbAitb3cSQsukJ6P3qxbJfWL8rXdUSh4/PqIclb0zIDBfxRVyjtC6I9irBlzR9A83QmFDjdeo5KQ2awkL2Wc5aa2swdxsBratx5crZUrRpA1PMHLND9ALdtHCnklbdby3CZ4dEzMR7W8PwC3rXLq/duxkmW7uIfcQVAsc60R4BKQPQ5R6HOLvasOen59vVbNIVQKxuuKKrmGp0mbMZ9x5XJFc4hYX9Gdvi4IeFSrtclV/7rRt5TKt76IvUHsJbNwqo+mTh8AOZqUsH8ZCFCa2hBgx7uOr/zMl2uW+cQVQOeMOV+3bS9eVEj/p6lDKMY1YCpDTduMMjxR7xMHoMRqOmh0mZpLwuM+3IlzFtLt/q8LRBaiIbq86BroVvxe02pbCphXV+ZCJMa5x/QWpf2QDd+R0OWEcnzTBYla8IwXvpxZrIQo8zQXNcOdnz7a+VTvGLCkrBEGhunGpU5U8YdQBk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
