travis:
  secure:
    BINSTAR_TOKEN: 1JGNPCU7o4sxPOFOiirDaTZdPGCzpcsPyiuzszIgmO7dIQfTZ4lQdF+X8Tp/qLNC5GLcHHBv/uPN1hkhLdiLldxw9O2jeoloFCAftw9IJHfWw7SsKTYhcOz3szpUxNqTqQ1SaI7FgoDhjiE8CoFECSqf4HAAgRNhKt/ahrw6+CY+zL0Rfl6uBUcYLOcpM9OMJeBlSt0yj2Uk3Mx42NYVUHtkUXpT8higN/AbedNOvja2UiN7m+Y6CEtfKBBuSXesmFlRku9O2yJUMki+P5yDQlXzXncL8UFo98O6c6DJUw82+bS/bcSeZa+mg1SPW4kkoDy3aWP1ukOAiY9OjmLwNMaZuYe1B8U0itkEYTsY2mKLMDoxTjcvAKIUzmllqHrow9/GME97XL56NGZopYoPuYL9Iv7jjyge8kEp9aqrCq7zk+P4YpDJqV/J0o3zOSs8V6DIct0gZ1Hp5qyDjFnGQ++NPje0qwSCFK0OXGN3DN/21nVvNcsjicNHwNGI9vTXMYOEtreI9oErmvaeiS/OzXFSkJudygfBFiXwV6Y6Aw7JxhpC81eO+XUsbTVpLL1ktIcNc+ImiJBd1vxlKAjGnEcNEi+4cPTUuz+Xurg8lLOFIu8DHVCN1b2Jd73Jmc3g70HVdIaZt+EFK6O/sfEaP2CfXIqwUkP84BNYfB244ek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
