travis:
  secure:
    BINSTAR_TOKEN: fxhZsydgFdLv0+3SYaRg450t1FwStdI6zYL4nJPpznY1opNljaRzOZxBk1E3is9jkvxOelfIwM0HWTfuInJCqP1VYahsNYLdGXl3OmeYf9Ac5B0O5WxwPVYRvSxk3slTZglnZS3FggWzolsSqRKQlJH75ekxppQqVDdaXTOy9/E9Jd4ZpvQvRY5gjiaYA1pIRZo0SeA4EXUgRfbLK8C4y1KmnpF7dlTtaOFOkAvbYINhAK3DdPYLi7bRaVdUT5gOnQZ9Pf72U3o73fpGPcaZrroKB9n7uSNIpZyIWvgzIbBSm47Ked2OyIwoX2Z91tggkBjTouWCiR9F2Eut+bqKJRVPpjddk8bALY78K/AgOKYkqclJwj9nhUktxYtj5t6TUqtrxqbuWxvDQ+/FsfllRBWcN32bPKejkhZZQp8bNI8nCo7CV5nc5CgOIuigEKAC9Pa0VRRaxHj4xTPSvyNT47FzvinXx9jy0Wn5kTs2jQdR8WNo2iDufokPTsKIH8/fJ6OgQ/qUFtpXtsWBouJzs2LDNUIYEgpUyz3liqE8OK5QfCawBJGu4ma2rT5R3UOfblH8y2N0E0QiP0YBnKW4vm+7/a0qRn679V+lR9xhArmwYIFo06zOdPHug9JgURjeCinZ0Z/d6vFNpk0wSZFMztOwnUzB+rfEIr10Ncp/jI4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
