travis:
  secure:
    BINSTAR_TOKEN: fpSrie1OJTf34jHfsSebXBAHexzAG/qHfOoKy3/RhCvxhQ51B1epuApBQXII7KU5Eaetuy9a+rj1KRD5HEvrbJkN7mcVDzhefu0si0T77SFuuQofxb2NzeOPDo0rbtkSDjDTbLUq9Ab5VjUY7vPdQJ+1srRTZv0ExGxW5K8iOaPphJ98Qm/1vCNZZlLPQSfdMLlGaxTcX99KChVGgkruGfdmBSZO9wTxYXgiN0YjrDbzprleG0OLXMgCZt97Gfybk3UIjlHoCeL3HvTwLAhylhSRcqCDkdoGciEmNF4K+TNUnodg1MOGjKElDV/jDA5e9YMZLewVEdogk96DQpytNoWf/byu4T03wYUz7i/UKYrhksCt9g66slXDtScjq0edteWbH8WfR3pi0EpHDGqBxlx/cDNML6e7h/vFtKi3Qnk/vcdTvG3gPPbCEZGQFuNyN6bFTLzvrENlD1m04WNdxg/Vzt54sulUKCa8ub+g3AGTgaUdScyXHuX9+7J2D74sICN1xNSvUDUBu5EPMkrj5Xdi5BywYY1M/VN0i2q7C7Aq8JyRuPQv8emBmzdm5OrsLae8FR2rQLCs/pZsE5dRegYXAeRrg8psGg6FdLrvfSu5lAwp2FrecwBj+EB1yPvHEKrZSMgXxcKbQT60oDe103Wj6tfRUThRAZOROrRzNgE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
